version: '3'
services:
  strapi:
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      SERVE_ADMIN_PANEL: 'true'
      MQ_CLIENT_NAME: Kafka
      KAFKA_BROKERS: '192.168.88.93:29092'
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
