version: '3'
services:
  strapi:
    environment:
      DATABASE_CLIENT: mongo
      # DATABASE_URL: mongodb://strapi:strapi@mongo/strapi?authenticationDatabase=admin
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      # DATABASE_USERNAME: user
      # DATABASE_PASSWORD: useruser
      # DATABASE_NAME: event
      # DATABASE_HOST: host.docker.internal
      # AUTHENTICATION_DATABASE: admin
      # DATABASE_SSL: 'true'
      SERVE_ADMIN_PANEL: 'true'
      NODE_ENV: production
      # MQ_CLIENT_NAME: Kafka
      # KAFKA_BROKERS: '192.168.88.93:29092'
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    ports:
      - '27817:27017'
    volumes:
      - ./data-mongo:/data/db
