/* tslint:disable */
/* eslint-disable */
/**
 * Tutor
 * Event Manager Backend service is based on Strapi v3 JS framework.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aram@dasmeta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewEvent
 */
export interface NewEvent {
    /**
     * 
     * @type {string}
     * @memberof NewEvent
     */
    name?: any;
    /**
     * 
     * @type {Date}
     * @memberof NewEvent
     */
    publishedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof NewEvent
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof NewEvent
     */
    updatedBy?: any;
}
